version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memecoin_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: memecoin_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: memecoin_db
    restart: always
    environment:
      MYSQL_DATABASE: memecoin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  db_data:
